"""Models for ESI Link responses.

These models represent the data returned by ESI endpoints. The model is named after the
operation_id for the endpoint. Where the response model is a container,
items in the container will be named with the suffix "Item" to distinguish them from the
container itself.

Fields may also be added to the container that have data from the query parameters or
other metadata that is not directly from the ESI response, but is relevant to the calculations.

The data may be organized in collections in a different form than the raw ESI response
for ease of use in calculations. For example, market orders may be collected by type ID
and buy/sell status, rather than being a flat list of orders as returned by ESI.

This is a limited set of models defined for convienience in the Argus modules,
and is not intended to be a comprehensive set of models for all ESI responses. For a
more comprehensive information on the response data from the EVE Esi, see the schema docs.
"""

from abc import abstractmethod
from dataclasses import dataclass
from typing import Any, Literal, Self, TypedDict

from pydantic import BaseModel

from esi_link.models_and_protocols import ResponseData


class EsiDataModel(BaseModel):
    """Base class for ESI data models."""

    operation_id: str
    """The ESI operation ID that this model represents."""
    response_date: str
    """The date and time when the response was generated by the ESI server, as an RFC 2822 string."""
    received_at: int
    """The date and time when the data was received from ESI, as a Unix timestamp in nanoseconds."""

    @classmethod
    @abstractmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create an instance of the model from ESI response data."""
        raise NotImplementedError("Subclasses must implement from_response_data method")


@dataclass(slots=True)
class GetMarketPricesItem:
    type_id: int
    """The item type ID of the market price."""
    adjusted_price: float | None
    """The adjusted price of the item, calculated as a volume-weighted average of recent market prices."""
    average_price: float | None
    """The average price of the item, calculated as a simple average of recent market prices."""


class GetMarketPrices(EsiDataModel):
    prices: dict[int, GetMarketPricesItem]
    """A mapping of item type IDs to their corresponding market price information."""

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetMarketPrices instance from ESI response data."""
        operation_id = "GetMarketPrices"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        prices_dict: dict[int, GetMarketPricesItem] = {}
        for item in response_data.data:
            price_item = GetMarketPricesItem(**item)
            prices_dict[price_item.type_id] = price_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "prices": prices_dict,
            }
        )


@dataclass(slots=True)
class GetMarketsRegionIdHistoryItem:
    average: float
    date: str
    highest: float
    lowest: float
    order_count: int
    volume: float


class GetMarketsRegionIdHistory(EsiDataModel):
    region_id: int
    type_id: int
    history: dict[str, GetMarketsRegionIdHistoryItem]

    @property
    def most_recent_date(self) -> str | None:
        """Get the most recent date from the market history data."""
        return next(iter(self.history.keys())) if self.history else None

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetMarketsRegionIdHistory instance from ESI response data."""
        operation_id = "GetMarketsRegionIdHistory"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        region_id = int(response_data.request.path_parameters["region_id"])
        type_id = int(response_data.request.path_parameters["type_id"])
        history_dict: dict[str, GetMarketsRegionIdHistoryItem] = {}
        sorted_data = sorted(response_data.data, key=lambda x: x["date"], reverse=True)
        for item in sorted_data:
            history_item = GetMarketsRegionIdHistoryItem(**item)
            history_dict[history_item.date] = history_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "region_id": region_id,
                "type_id": type_id,
                "history": history_dict,
            }
        )


@dataclass(slots=True)
class GetMarketsRegionIdOrdersItem:
    """Represents a market order detail."""

    duration: int
    is_buy_order: bool
    issued: str
    location_id: int
    min_volume: int
    order_id: int
    price: float
    range: str
    system_id: int
    type_id: int
    volume_remain: int
    volume_total: int


@dataclass(slots=True)
class CollectedMarketOrders:
    """Represents collected market orders for a specific region and type."""

    region_id: int
    type_id: int
    buy_orders: list[GetMarketsRegionIdOrdersItem]
    sell_orders: list[GetMarketsRegionIdOrdersItem]


class GetMarketsRegionIdOrders(EsiDataModel):
    """Represents market orders for a specific region."""

    region_id: int
    orders: dict[int, CollectedMarketOrders]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetMarketsRegionIdOrders instance from ESI response data."""
        operation_id = "GetMarketsRegionIdOrders"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        region_id = int(response_data.request.path_parameters["region_id"])
        orders_by_type: dict[int, CollectedMarketOrders] = {}
        for item in response_data.data:
            order_item = GetMarketsRegionIdOrdersItem(**item)
            type_id = order_item.type_id
            if type_id not in orders_by_type:
                orders_by_type[type_id] = CollectedMarketOrders(
                    region_id=region_id,
                    type_id=type_id,
                    buy_orders=[],
                    sell_orders=[],
                )
            if order_item.is_buy_order:
                orders_by_type[type_id].buy_orders.append(order_item)
            else:
                orders_by_type[type_id].sell_orders.append(order_item)
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "region_id": region_id,
                "orders": orders_by_type,
            }
        )


class CostIndexActivity(TypedDict):
    activity: Literal[
        "manufacturing",
        "researching_time_efficiency",
        "researching_material_efficiency",
        "copying",
        "invention",
        "reaction",
    ]
    cost_index: float


@dataclass(slots=True)
class GetIndustrySystemsItem:
    solar_system_id: int
    cost_indices: list[CostIndexActivity]

    @property
    def cost_index_by_activity(self) -> dict[str, float | str]:
        """Get a mapping of activity names to their corresponding cost indices."""
        for ci in self.cost_indices:
            print(ci)
        return {ci["activity"]: ci["cost_index"] for ci in self.cost_indices}


class GetIndustrySystems(EsiDataModel):
    systems: dict[int, GetIndustrySystemsItem]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetIndustrySystems instance from ESI response data."""
        operation_id = "GetIndustrySystems"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_dict: dict[int, GetIndustrySystemsItem] = {}
        for item in response_data.data:
            system_item = GetIndustrySystemsItem(**item)
            data_dict[system_item.solar_system_id] = system_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "systems": data_dict,
            }
        )


@dataclass(slots=True)
class GetCorporationsCorporationIdBlueprintsItem:
    item_id: int
    location_flag: str
    location_id: int
    material_efficiency: int
    quantity: int
    runs: int
    time_efficiency: int
    type_id: int


class GetCorporationsCorporationIdBlueprints(EsiDataModel):
    corporation_id: int
    blueprints: dict[int, list[GetCorporationsCorporationIdBlueprintsItem]]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCorporationsCorporationIdBlueprints instance from ESI response data."""
        operation_id = "GetCorporationsCorporationIdBlueprints"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_dict: dict[int, list[GetCorporationsCorporationIdBlueprintsItem]] = {}
        for item in response_data.data:
            blueprint_item = GetCorporationsCorporationIdBlueprintsItem(**item)
            if blueprint_item.type_id not in data_dict:
                data_dict[blueprint_item.type_id] = []
            data_dict[blueprint_item.type_id].append(blueprint_item)
        model_dict: dict[str, Any] = {
            "operation_id": operation_id,
            "response_date": response_data.response_date,
            "received_at": response_data.received_at,
            "corporation_id": int(
                response_data.request.path_parameters["corporation_id"]
            ),
            "blueprints": data_dict,
        }
        return cls.model_validate(model_dict)


@dataclass(slots=True)
class GetCharactersCharacterIdBlueprintsItem:
    item_id: int
    location_flag: str
    location_id: int
    material_efficiency: int
    quantity: int
    runs: int
    time_efficiency: int
    type_id: int


class GetCharactersCharacterIdBlueprints(EsiDataModel):
    character_id: int
    blueprints: dict[int, list[GetCharactersCharacterIdBlueprintsItem]]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCharactersCharacterIdBlueprints instance from ESI response data."""
        operation_id = "GetCharactersCharacterIdBlueprints"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_dict: dict[int, list[GetCharactersCharacterIdBlueprintsItem]] = {}
        for item in response_data.data:
            blueprint_item = GetCharactersCharacterIdBlueprintsItem(**item)
            if blueprint_item.type_id not in data_dict:
                data_dict[blueprint_item.type_id] = []
            data_dict[blueprint_item.type_id].append(blueprint_item)
        model_dict: dict[str, Any] = {
            "operation_id": operation_id,
            "response_date": response_data.response_date,
            "received_at": response_data.received_at,
            "character_id": int(response_data.request.path_parameters["character_id"]),
            "blueprints": data_dict,
        }
        return cls.model_validate(model_dict)
