import logging
from collections.abc import Sequence
from typing import Any

import httpx2
from jwt import ExpiredSignatureError, PyJWKClient, decode, get_unverified_header

from esi_link.httpx2.esi_examples.models.auth import (
    OauthTokenTD,
    ValidatedTokenTD,
)

logger = logging.getLogger(__name__)


def request_token(
    client_id: str,
    authorization_code: str,
    code_verifier: str,
    token_endpoint: str,
    user_agent: str,
) -> OauthTokenTD:
    """Takes an authorization code and code verifier and exchanges it for an access token and refresh token."""
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "grant_type": "authorization_code",
        "code": authorization_code,
        "client_id": client_id,
        "code_verifier": code_verifier,
    }
    response = httpx2.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = response.json()

    return result


def refresh_token(
    refresh_token: str,
    client_id: str,
    token_endpoint: str,
    user_agent: str,
) -> OauthTokenTD:
    """Takes a refresh token and exchanges it for a new oauth token."""
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "client_id": client_id,
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }
    response = httpx2.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = response.json()
    return result


def revoke_refresh_token(
    refresh_token: str,
    revocation_endpoint: str,
    client_id: str,
    user_agent: str,
) -> Any:
    """Revoke a refresh token.

    Im not sure how to tell for sure if the refresh token got revoked, except to test a
    refresh after revocation and see if it fails. The SSO returns a 200 OK response even
    if the token is invalid or already revoked, so we have to rely on testing the token
    after revocation to confirm it worked.
    """
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "token": refresh_token,
        "token_type_hint": "refresh_token",
        "client_id": client_id,
    }
    response = httpx2.post(revocation_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    return response.json()


async def async_request_token(
    client_id: str,
    authorization_code: str,
    code_verifier: str,
    token_endpoint: str,
    user_agent: str,
    client_session: httpx2.AsyncClient,
) -> OauthTokenTD:
    """Takes an authorization code and code verifier and exchanges it for an access token and refresh token.

    Args:
        client_id: The client ID of the application.
        authorization_code: The authorization code received from the SSO.
        code_verifier: The code verifier used to generate the code challenge, as generated by `generate_code_challenge`.
        token_endpoint: The token endpoint URI for exchanging the authorization code.
        user_agent: The User-Agent string to use in the request.
        client_session: The httpx2.AsyncClient session for making requests.

    Returns:
        A dictionary containing the access token and refresh token.

    Raises:
        ValueError: If client_session is not initialized.
        httpx2.HTTPStatusError: If the token request fails.
    """
    if not client_session:
        raise ValueError("client_session must be initialized to request token.")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "grant_type": "authorization_code",
        "code": authorization_code,
        "client_id": client_id,
        "code_verifier": code_verifier,
    }
    response = await client_session.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = await response.json()

    return result


async def async_refresh_token(
    refresh_token: str,
    client_id: str,
    token_endpoint: str,
    user_agent: str,
    client_session: httpx2.AsyncClient,
) -> OauthTokenTD:
    """Takes a refresh token and exchanges it for a new oauth token.

    Args:
        refresh_token: The refresh token portion of the OAuth2 token.
        client_id: The client ID of the application.
        token_endpoint: The token endpoint URI for refreshing tokens.
        user_agent: The User-Agent string to use in the request.
        client_session: The httpx2.AsyncClient session for making requests.

    Returns:
        A dictionary containing the new access token and refresh token.

    Raises:
        ValueError: If client_session is not initialized.
        httpx2.HTTPStatusError: If the token request fails.
    """
    if not client_session:
        raise ValueError("client_session must be initialized to refresh token.")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "client_id": client_id,
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }
    response = await client_session.post(token_endpoint, headers=headers, data=payload)
    response.raise_for_status()
    result = await response.json()
    return result


async def async_revoke_refresh_token(
    refresh_token: str,
    revocation_endpoint: str,
    client_id: str,
    user_agent: str,
    client_session: httpx2.AsyncClient,
) -> Any:
    """Revoke a refresh token.

    Im not sure how to tell for sure if the refresh token got revoked, except to test a
    refresh after revocation and see if it fails. The SSO returns a 200 OK response even
    if the token is invalid or already revoked, so we have to rely on testing the token
    after revocation to confirm it worked.

    Args:
        refresh_token: The refresh token to revoke.
        revocation_endpoint: The revocation endpoint URI.
        client_id: The client ID of the application.
        user_agent: The User-Agent string to use in the request.
        client_session: The httpx2.AsyncClient session for making requests.

    Raises:
        httpx2.HTTPStatusError: If the revocation request fails.
    """
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": user_agent,
    }
    payload: dict[str, str] = {
        "token": refresh_token,
        "token_type_hint": "refresh_token",
        "client_id": client_id,
    }

    response = await client_session.post(
        revocation_endpoint, headers=headers, data=payload
    )
    response.raise_for_status()
    if response.status_code == 200:
        logger.info("Token revoked successfully")


def validate_jwt_token(
    access_token: str,
    jwks_client: PyJWKClient | None,
    audience: str,
    issuers: Sequence[str],
    user_agent: str,
    jwks_uri: str = "",
) -> ValidatedTokenTD:
    """Validates and decodes a JWT Token.

    Args:
        access_token: The JWT token to validate.
        jwks_uri: The JWKS URI to fetch signing keys from.
        jwks_client: An optional PyJWKClient instance to use for fetching keys.
            If None, a new client will be created.
        audience: Expected audience for the token.
        issuers: Valid issuers for the token.
        user_agent: The User-Agent string to use in requests.

    Returns:
        The content of the validated JWT access token.

    Raises:
        ValueError: If jwks_uri is not provided when jwks_client is None.
        jwt.ExpiredSignatureError: If the token has expired.
        jwt.InvalidTokenError: If the token is invalid.
        Exception: If any other error occurs.
    """
    headers = {"User-Agent": user_agent}
    # NOTE the jwks_client can cache the keys, so we dont have to fetch them every time.
    # Pass in a jwks_client if you have one.
    if jwks_client is None:
        if not jwks_uri:
            raise ValueError("jwks_uri must be provided if jwks_client is None")
        jwks_client = PyJWKClient(jwks_uri, headers=headers)
    unverified_header = get_unverified_header(access_token)
    kid = unverified_header["kid"]
    alg = unverified_header["alg"]
    signing_key = jwks_client.get_signing_key(kid).key
    try:
        # Decode and validate the token
        valid_decoded_token = decode(  # type: ignore
            jwt=access_token,
            key=signing_key,
            algorithms=[alg],
            audience=audience,
            issuer=issuers,
            options={"verify_aud": True, "verify_iss": True},
        )

        return ValidatedTokenTD(**valid_decoded_token)
    except ExpiredSignatureError as e:
        logger.error("Token has expired")
        raise e
    except Exception as e:
        logger.error(f"Invalid token or other error: {e}")
        raise e
