"""UrlGenerator implementation for generating urls and cache keys for ESI requests based on an indexed schema."""

from uuid import UUID, uuid5

from esi_link.v2 import ESI_LINK_NAMESPACE
from esi_link.v2.helpers.canonicalize_url import canonicalize_url
from esi_link.v2.models import (
    EsiRequest,
    GeneratedUrlInfo,
    IndexedEsiSchema,
    UrlGeneratorProtocol,
)


class UrlGenerator(UrlGeneratorProtocol):
    def __init__(self, schema: IndexedEsiSchema):
        """Initialize the UrlGenerator with the indexed schema."""
        self.schema = schema

    def generate_path_url(self, request: EsiRequest) -> str:
        """Generate the url path for an ESI request based on its parameters.\
            
        This url does not contain query parameters, and is not suitable for generateing 
        a cache key. It is used as the url argument for http requests, assuming that 
        query parameters are sent separately.
        """
        base_url = self.schema.base_url
        path_template = self.schema.operations[request.operation_id].path
        path_parameters = request.path_parameters or {}
        return _path_url(
            base_url=base_url,
            path_template=path_template,
            path_parameters=path_parameters,
        )

    def generate_cache_url(self, request: EsiRequest) -> str:
        """Generate the url to use for cache key generation for an ESI request based on its parameters.

        This url should contain all path and most query parameters, and should be
        consistent for requests that should share a cache key. It is used for generating
        cache keys, and is not necessarily the same as the url used for making the http request.

        NOTE: Validate the request before generating the cache url, to ensure that all
        required parameters are present and correctly formatted, to avoid generating
        different cache urls for requests that should share a cache key.
        """
        path_url = self.generate_path_url(request)
        query_parameters = request.query_parameters or {}
        cache_url = _cache_url(path_url, query_parameters)
        return cache_url

    def generate_cache_key(self, request: EsiRequest) -> UUID:
        """Generate a cache key for an ESI request based on its parameters.

        The key is usually generated by hashing the url generated by generate_cache_url,
        but can be any UUID that is consistently generated for requests that should share
        a cache key.
        """
        cache_url = self.generate_cache_url(request)
        cache_key = _cache_key_from_url(cache_url)
        return cache_key

    def generate_url_info(self, request: EsiRequest) -> GeneratedUrlInfo:
        """Generate all url related information for an ESI request.

        This is a convenience method that generates the path url, cache url, and cache key
        for an ESI request in one call, since these values are often needed together
        and share intermediate calculations.

        NOTE: Validate the request before generating the cache url, to ensure that all
        required parameters are present and correctly formatted, to avoid generating
        different cache urls for requests that should share a cache key.
        """
        base_url = self.schema.base_url
        path_template = self.schema.operations[request.operation_id].path
        path_parameters = request.path_parameters or {}
        path_url = _path_url(
            base_url=base_url,
            path_template=path_template,
            path_parameters=path_parameters,
        )
        query_parameters = request.query_parameters or {}
        cache_url = _cache_url(path_url, query_parameters)
        cache_key = _cache_key_from_url(cache_url)
        return GeneratedUrlInfo(
            path_url=path_url,
            cache_url=cache_url,
            cache_key=cache_key,
        )


def _path_url(
    base_url: str, path_template: str, path_parameters: dict[str, str | int | float]
) -> str:
    """Helper function to generate the url path for an ESI request."""
    path = path_template.format(**path_parameters)
    return f"{base_url.strip('/')}/{path.strip('/')}"


def _cache_url(path_url: str, query_parameters: dict[str, str | int | float]) -> str:
    """Helper function to generate the cache url for an ESI request."""
    # Sort keys so url is stable regardless of dict insertion order
    query_items = sorted(query_parameters.items(), key=lambda kv: kv[0])
    query_string = "&".join([f"{key}={value}" for key, value in query_items])
    cache_url = f"{path_url}?{query_string}" if query_string else path_url
    cache_url = canonicalize_url(cache_url)
    return cache_url


def _cache_key_from_url(url: str) -> UUID:
    """Generate a cache key UUID from a URL."""
    # canonical_url = canonicalize_url(url)
    return uuid5(ESI_LINK_NAMESPACE, url)
